### ISSUE TITLE
Cached 302 responses do not keep valid `next` property

### ISSUE THREAD

**Issue by Querela** [reclosedev/requests-cache#321]
### The problem
_A description of what the bug is, including a complete traceback (if applicable)_

I want to cache **`302`** redirect responses from `HEAD` requests. I later found that the `.next` property is not accessible.

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/***/.local/share/virtualenvs/***/lib/python3.9/site-packages/requests/models.py", line 725, in next
    return self._next
AttributeError: 'CachedResponse' object has no attribute '_next'
```

### Expected behavior
_A description of what you expected to happen_

The `.next` property on the `CachedResponse` should be set.

### Steps to reproduce the behavior
_With a complete code example, if possible_

```python
import requests
from requests_cache import CachedSession
from requests_cache.backends.sqlite import DbCache

backend = DbCache(".cache.sqlite")
sess = CachedSession(backend=backend, allowable_codes=(200, 302))
#requests.utils.add_dict_to_cookiejar(sess.cookies, REQ_COOKIES)
#sess.headers.update(REQ_HEADERS)

url = "http://httpbingo.org/absolute-redirect/6"

resp = sess.head(url)
assert resp.next.url == 'http://httpbingo.org/absolute-redirect/5'

resp = sess.head(url)
assert resp.headers["location"] == 'http://httpbingo.org/absolute-redirect/5'
resp.next.url  # <-- fails
```
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/***/.local/share/virtualenvs/***/lib/python3.9/site-packages/requests/models.py", line 725, in next
    return self._next
AttributeError: 'CachedResponse' object has no attribute '_next'
```

### Workarounds
_Is there an existing workaround for this issue?_

Yes, the `.headers` are correctly set and the `Location` field contains the redirect url.

### Environment
- requests-cache version: 0.7.1
- Python version: 3.9.5
- Platform: WSL2 (Ubuntu 20)

**Comment by JWCook** [comment]
Thanks for reporting! I'll get that fixed shortly.

**Comment by JWCook** [comment]
This has been fixed in #324. You can try out the pre-release build with:
```
pip install requests-cache==0.7.2b0
```

Let me know if that works for you, and I'll push out another patch release within a week or so.

**Comment by Querela** [comment]
Thank you, I will test it and write back

**Comment by Querela** [comment]
Ok. It worked correctly with version `0.7.2b0`.

**Comment by JWCook** [comment]
This is now in the latest stable release (`0.7.2`).
